//@flow
export default {
    HUNDRED_FREE_APPS_API: process.env.REACT_APP_HUNDRED_FREE_APPS_API,
    RECOMMENDED_APPS_API: process.env.REACT_APP_RECOMMENDED_APPS_API,
    LOOKUP_API: process.env.REACT_APP_LOOKUP_API
}